/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

// Context struct for Context
type Context struct {
	// Provider type
	Provider string `json:"provider"`
	// Additional provider-specific configuration
	Properties map[string]interface{} `json:"properties"`
}
