/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

// Commit struct for Commit
type Commit struct {
	// Commit identifier
	Id string `json:"id"`
	// Additional commit metadata
	Properties map[string]interface{} `json:"properties"`
}
