/*
Dit API

REST API exposed by the local `dit-server` Docker container and consumed by the Dit CLI (`d3`) and other in-process clients.  The server listens on a loopback port only and is **not intended for remote use**; there is no authentication, authorization, or transport security. For multi-tenant or cross-host scenarios, deploy the separate `dit-remote-server` instead, which fronts this API with auth.  Operation IDs follow `verbResource` naming (e.g. `listRepositories`, `createCommit`) and map 1:1 to generated client methods.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ditclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CommitStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitStatus{}

// CommitStatus struct for CommitStatus
type CommitStatus struct {
	// Logical size of data referenced by commit
	LogicalSize int64 `json:"logicalSize"`
	// Actual size of data referenced by commit
	ActualSize int64 `json:"actualSize"`
	// Amount of data uniquely held by this commit
	UniqueSize int64 `json:"uniqueSize"`
	// Whether this commit can be used as the source of an operation or whether it's still being created
	Ready bool `json:"ready"`
	// If commit failed to be created, error string explaining why
	Error *string `json:"error,omitempty"`
}

type _CommitStatus CommitStatus

// NewCommitStatus instantiates a new CommitStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitStatus(logicalSize int64, actualSize int64, uniqueSize int64, ready bool) *CommitStatus {
	this := CommitStatus{}
	this.LogicalSize = logicalSize
	this.ActualSize = actualSize
	this.UniqueSize = uniqueSize
	this.Ready = ready
	return &this
}

// NewCommitStatusWithDefaults instantiates a new CommitStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitStatusWithDefaults() *CommitStatus {
	this := CommitStatus{}
	return &this
}

// GetLogicalSize returns the LogicalSize field value
func (o *CommitStatus) GetLogicalSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LogicalSize
}

// GetLogicalSizeOk returns a tuple with the LogicalSize field value
// and a boolean to check if the value has been set.
func (o *CommitStatus) GetLogicalSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogicalSize, true
}

// SetLogicalSize sets field value
func (o *CommitStatus) SetLogicalSize(v int64) {
	o.LogicalSize = v
}

// GetActualSize returns the ActualSize field value
func (o *CommitStatus) GetActualSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ActualSize
}

// GetActualSizeOk returns a tuple with the ActualSize field value
// and a boolean to check if the value has been set.
func (o *CommitStatus) GetActualSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualSize, true
}

// SetActualSize sets field value
func (o *CommitStatus) SetActualSize(v int64) {
	o.ActualSize = v
}

// GetUniqueSize returns the UniqueSize field value
func (o *CommitStatus) GetUniqueSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UniqueSize
}

// GetUniqueSizeOk returns a tuple with the UniqueSize field value
// and a boolean to check if the value has been set.
func (o *CommitStatus) GetUniqueSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UniqueSize, true
}

// SetUniqueSize sets field value
func (o *CommitStatus) SetUniqueSize(v int64) {
	o.UniqueSize = v
}

// GetReady returns the Ready field value
func (o *CommitStatus) GetReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ready
}

// GetReadyOk returns a tuple with the Ready field value
// and a boolean to check if the value has been set.
func (o *CommitStatus) GetReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ready, true
}

// SetReady sets field value
func (o *CommitStatus) SetReady(v bool) {
	o.Ready = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *CommitStatus) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitStatus) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *CommitStatus) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *CommitStatus) SetError(v string) {
	o.Error = &v
}

func (o CommitStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["logicalSize"] = o.LogicalSize
	toSerialize["actualSize"] = o.ActualSize
	toSerialize["uniqueSize"] = o.UniqueSize
	toSerialize["ready"] = o.Ready
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *CommitStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logicalSize",
		"actualSize",
		"uniqueSize",
		"ready",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommitStatus := _CommitStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommitStatus)

	if err != nil {
		return err
	}

	*o = CommitStatus(varCommitStatus)

	return err
}

type NullableCommitStatus struct {
	value *CommitStatus
	isSet bool
}

func (v NullableCommitStatus) Get() *CommitStatus {
	return v.value
}

func (v *NullableCommitStatus) Set(val *CommitStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitStatus(val *CommitStatus) *NullableCommitStatus {
	return &NullableCommitStatus{value: val, isSet: true}
}

func (v NullableCommitStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
