/*
Datadatdat API

REST API exposed by the local `datadatdat-server` Docker container and consumed by the Datadatdat CLI (`d3`) and other in-process clients.  The server listens on a loopback port only and is **not intended for remote use**; there is no authentication, authorization, or transport security. For multi-tenant or cross-host scenarios, deploy the separate `datadatdat-remote-server` instead, which fronts this API with auth.  Operation IDs follow `verbResource` naming (e.g. `listRepositories`, `createCommit`) and map 1:1 to generated client methods.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ProgressEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgressEntry{}

// ProgressEntry struct for ProgressEntry
type ProgressEntry struct {
	// Sequenced entry identifier
	Id int32 `json:"id"`
	// Entry type
	Type string `json:"type"`
	// Optional message for progress step
	Message *string `json:"message,omitempty"`
	// Optional percent for step
	Percent *int32 `json:"percent,omitempty"`
}

type _ProgressEntry ProgressEntry

// NewProgressEntry instantiates a new ProgressEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgressEntry(id int32, type_ string) *ProgressEntry {
	this := ProgressEntry{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewProgressEntryWithDefaults instantiates a new ProgressEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgressEntryWithDefaults() *ProgressEntry {
	this := ProgressEntry{}
	return &this
}

// GetId returns the Id field value
func (o *ProgressEntry) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ProgressEntry) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ProgressEntry) SetId(v int32) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ProgressEntry) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ProgressEntry) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ProgressEntry) SetType(v string) {
	o.Type = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ProgressEntry) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgressEntry) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ProgressEntry) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ProgressEntry) SetMessage(v string) {
	o.Message = &v
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *ProgressEntry) GetPercent() int32 {
	if o == nil || IsNil(o.Percent) {
		var ret int32
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgressEntry) GetPercentOk() (*int32, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *ProgressEntry) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given int32 and assigns it to the Percent field.
func (o *ProgressEntry) SetPercent(v int32) {
	o.Percent = &v
}

func (o ProgressEntry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgressEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	return toSerialize, nil
}

func (o *ProgressEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgressEntry := _ProgressEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProgressEntry)

	if err != nil {
		return err
	}

	*o = ProgressEntry(varProgressEntry)

	return err
}

type NullableProgressEntry struct {
	value *ProgressEntry
	isSet bool
}

func (v NullableProgressEntry) Get() *ProgressEntry {
	return v.value
}

func (v *NullableProgressEntry) Set(val *ProgressEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableProgressEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableProgressEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgressEntry(val *ProgressEntry) *NullableProgressEntry {
	return &NullableProgressEntry{value: val, isSet: true}
}

func (v NullableProgressEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgressEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
