/*
Datadatdat API

REST API exposed by the local `datadatdat-server` Docker container and consumed by the Datadatdat CLI (`d3`) and other in-process clients.  The server listens on a loopback port only and is **not intended for remote use**; there is no authentication, authorization, or transport security. For multi-tenant or cross-host scenarios, deploy the separate `datadatdat-remote-server` instead, which fronts this API with auth.  Operation IDs follow `verbResource` naming (e.g. `listRepositories`, `createCommit`) and map 1:1 to generated client methods.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the VolumeStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumeStatus{}

// VolumeStatus struct for VolumeStatus
type VolumeStatus struct {
	// Volume name
	Name string `json:"name"`
	// Logical size consumed by the volume
	LogicalSize int64 `json:"logicalSize"`
	// Actual (compressed) size used by the volume
	ActualSize int64 `json:"actualSize"`
	// Client-specific properties
	Properties map[string]interface{} `json:"properties"`
	// True if the volume is ready for use in a runtime environment
	Ready bool `json:"ready"`
	// Optional error message if volume asynchronously failed to be created
	Error *string `json:"error,omitempty"`
}

type _VolumeStatus VolumeStatus

// NewVolumeStatus instantiates a new VolumeStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumeStatus(name string, logicalSize int64, actualSize int64, properties map[string]interface{}, ready bool) *VolumeStatus {
	this := VolumeStatus{}
	this.Name = name
	this.LogicalSize = logicalSize
	this.ActualSize = actualSize
	this.Properties = properties
	this.Ready = ready
	return &this
}

// NewVolumeStatusWithDefaults instantiates a new VolumeStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumeStatusWithDefaults() *VolumeStatus {
	this := VolumeStatus{}
	return &this
}

// GetName returns the Name field value
func (o *VolumeStatus) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VolumeStatus) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VolumeStatus) SetName(v string) {
	o.Name = v
}

// GetLogicalSize returns the LogicalSize field value
func (o *VolumeStatus) GetLogicalSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LogicalSize
}

// GetLogicalSizeOk returns a tuple with the LogicalSize field value
// and a boolean to check if the value has been set.
func (o *VolumeStatus) GetLogicalSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogicalSize, true
}

// SetLogicalSize sets field value
func (o *VolumeStatus) SetLogicalSize(v int64) {
	o.LogicalSize = v
}

// GetActualSize returns the ActualSize field value
func (o *VolumeStatus) GetActualSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ActualSize
}

// GetActualSizeOk returns a tuple with the ActualSize field value
// and a boolean to check if the value has been set.
func (o *VolumeStatus) GetActualSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActualSize, true
}

// SetActualSize sets field value
func (o *VolumeStatus) SetActualSize(v int64) {
	o.ActualSize = v
}

// GetProperties returns the Properties field value
func (o *VolumeStatus) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *VolumeStatus) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *VolumeStatus) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

// GetReady returns the Ready field value
func (o *VolumeStatus) GetReady() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ready
}

// GetReadyOk returns a tuple with the Ready field value
// and a boolean to check if the value has been set.
func (o *VolumeStatus) GetReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ready, true
}

// SetReady sets field value
func (o *VolumeStatus) SetReady(v bool) {
	o.Ready = v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *VolumeStatus) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumeStatus) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *VolumeStatus) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *VolumeStatus) SetError(v string) {
	o.Error = &v
}

func (o VolumeStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumeStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["logicalSize"] = o.LogicalSize
	toSerialize["actualSize"] = o.ActualSize
	toSerialize["properties"] = o.Properties
	toSerialize["ready"] = o.Ready
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

func (o *VolumeStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"logicalSize",
		"actualSize",
		"properties",
		"ready",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVolumeStatus := _VolumeStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVolumeStatus)

	if err != nil {
		return err
	}

	*o = VolumeStatus(varVolumeStatus)

	return err
}

type NullableVolumeStatus struct {
	value *VolumeStatus
	isSet bool
}

func (v NullableVolumeStatus) Get() *VolumeStatus {
	return v.value
}

func (v *NullableVolumeStatus) Set(val *VolumeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumeStatus(val *VolumeStatus) *NullableVolumeStatus {
	return &NullableVolumeStatus{value: val, isSet: true}
}

func (v NullableVolumeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
