/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Datadatdatclient

// RemoteParameters struct for RemoteParameters
type RemoteParameters struct {
	// Remote type
	Provider string `json:"provider"`
	// Provider-specific remote properties
	Properties map[string]interface{} `json:"properties"`
}
