/*
Datadatdat API

REST API exposed by the local `datadatdat-server` Docker container and consumed by the Datadatdat CLI (`d3`) and other in-process clients.  The server listens on a loopback port only and is **not intended for remote use**; there is no authentication, authorization, or transport security. For multi-tenant or cross-host scenarios, deploy the separate `datadatdat-remote-server` instead, which fronts this API with auth.  Operation IDs follow `verbResource` naming (e.g. `listRepositories`, `createCommit`) and map 1:1 to generated client methods.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Remote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Remote{}

// Remote struct for Remote
type Remote struct {
	// Remote type
	Provider string `json:"provider"`
	// Name of remote
	Name string `json:"name"`
	// Provider-specific remote properties
	Properties map[string]interface{} `json:"properties"`
}

type _Remote Remote

// NewRemote instantiates a new Remote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemote(provider string, name string, properties map[string]interface{}) *Remote {
	this := Remote{}
	this.Provider = provider
	this.Name = name
	this.Properties = properties
	return &this
}

// NewRemoteWithDefaults instantiates a new Remote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteWithDefaults() *Remote {
	this := Remote{}
	return &this
}

// GetProvider returns the Provider field value
func (o *Remote) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *Remote) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *Remote) SetProvider(v string) {
	o.Provider = v
}

// GetName returns the Name field value
func (o *Remote) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Remote) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Remote) SetName(v string) {
	o.Name = v
}

// GetProperties returns the Properties field value
func (o *Remote) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *Remote) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *Remote) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

func (o Remote) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Remote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["name"] = o.Name
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *Remote) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"name",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemote := _Remote{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemote)

	if err != nil {
		return err
	}

	*o = Remote(varRemote)

	return err
}

type NullableRemote struct {
	value *Remote
	isSet bool
}

func (v NullableRemote) Get() *Remote {
	return v.value
}

func (v *NullableRemote) Set(val *Remote) {
	v.value = val
	v.isSet = true
}

func (v NullableRemote) IsSet() bool {
	return v.isSet
}

func (v *NullableRemote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemote(val *Remote) *NullableRemote {
	return &NullableRemote{value: val, isSet: true}
}

func (v NullableRemote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
