/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

// Operation struct for Operation
type Operation struct {
	// Unique identifier for the operation
	Id string `json:"id"`
	// Operation type
	Type string `json:"type"`
	// Current operation state
	State string `json:"state"`
	// Name of remote associated with the operation
	Remote string `json:"remote"`
	// Commit identifier being pushed or pulled
	CommitId string `json:"commitId"`
}
