/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

// Repository struct for Repository
type Repository struct {
	// Repository name
	Name string `json:"name"`
	// Client-specific properties
	Properties map[string]interface{} `json:"properties"`
}
