/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

// Remote struct for Remote
type Remote struct {
	// Remote type
	Provider string `json:"provider"`
	// Name of remote
	Name string `json:"name"`
	// Provider-specific remote properties
	Properties map[string]interface{} `json:"properties"`
}
