/*
Dit API

REST API exposed by the local `dit-server` Docker container and consumed by the Dit CLI (`d3`) and other in-process clients.  The server listens on a loopback port only and is **not intended for remote use**; there is no authentication, authorization, or transport security. For multi-tenant or cross-host scenarios, deploy the separate `dit-remote-server` instead, which fronts this API with auth.  Operation IDs follow `verbResource` naming (e.g. `listRepositories`, `createCommit`) and map 1:1 to generated client methods.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ditclient

import (
	"encoding/json"
)

// checks if the RepositoryStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepositoryStatus{}

// RepositoryStatus struct for RepositoryStatus
type RepositoryStatus struct {
	// The latest commit ID for the repository
	LastCommit *string `json:"lastCommit,omitempty"`
	// The source commit for the current state (last checkout or commit)
	SourceCommit *string `json:"sourceCommit,omitempty"`
}

// NewRepositoryStatus instantiates a new RepositoryStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepositoryStatus() *RepositoryStatus {
	this := RepositoryStatus{}
	return &this
}

// NewRepositoryStatusWithDefaults instantiates a new RepositoryStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepositoryStatusWithDefaults() *RepositoryStatus {
	this := RepositoryStatus{}
	return &this
}

// GetLastCommit returns the LastCommit field value if set, zero value otherwise.
func (o *RepositoryStatus) GetLastCommit() string {
	if o == nil || IsNil(o.LastCommit) {
		var ret string
		return ret
	}
	return *o.LastCommit
}

// GetLastCommitOk returns a tuple with the LastCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatus) GetLastCommitOk() (*string, bool) {
	if o == nil || IsNil(o.LastCommit) {
		return nil, false
	}
	return o.LastCommit, true
}

// HasLastCommit returns a boolean if a field has been set.
func (o *RepositoryStatus) HasLastCommit() bool {
	if o != nil && !IsNil(o.LastCommit) {
		return true
	}

	return false
}

// SetLastCommit gets a reference to the given string and assigns it to the LastCommit field.
func (o *RepositoryStatus) SetLastCommit(v string) {
	o.LastCommit = &v
}

// GetSourceCommit returns the SourceCommit field value if set, zero value otherwise.
func (o *RepositoryStatus) GetSourceCommit() string {
	if o == nil || IsNil(o.SourceCommit) {
		var ret string
		return ret
	}
	return *o.SourceCommit
}

// GetSourceCommitOk returns a tuple with the SourceCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RepositoryStatus) GetSourceCommitOk() (*string, bool) {
	if o == nil || IsNil(o.SourceCommit) {
		return nil, false
	}
	return o.SourceCommit, true
}

// HasSourceCommit returns a boolean if a field has been set.
func (o *RepositoryStatus) HasSourceCommit() bool {
	if o != nil && !IsNil(o.SourceCommit) {
		return true
	}

	return false
}

// SetSourceCommit gets a reference to the given string and assigns it to the SourceCommit field.
func (o *RepositoryStatus) SetSourceCommit(v string) {
	o.SourceCommit = &v
}

func (o RepositoryStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepositoryStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastCommit) {
		toSerialize["lastCommit"] = o.LastCommit
	}
	if !IsNil(o.SourceCommit) {
		toSerialize["sourceCommit"] = o.SourceCommit
	}
	return toSerialize, nil
}

type NullableRepositoryStatus struct {
	value *RepositoryStatus
	isSet bool
}

func (v NullableRepositoryStatus) Get() *RepositoryStatus {
	return v.value
}

func (v *NullableRepositoryStatus) Set(val *RepositoryStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRepositoryStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRepositoryStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepositoryStatus(val *RepositoryStatus) *NullableRepositoryStatus {
	return &NullableRepositoryStatus{value: val, isSet: true}
}

func (v NullableRepositoryStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepositoryStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
