/*
 * Datadatdat API
 *
 * API used by the Datadatdat CLI
 *
 * API version: 0.3.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

// CommitStatus struct for CommitStatus
type CommitStatus struct {
	// Logical size of data referenced by commit
	LogicalSize int64 `json:"logicalSize"`
	// Actual size of data referenced by commit
	ActualSize int64 `json:"actualSize"`
	// Amount of data uniquely held by this commit
	UniqueSize int64 `json:"uniqueSize"`
	// Whether this commit can be used as the source of an operation or whether it's still being created
	Ready bool `json:"ready"`
	// If commit failed to be created, error string explaining why
	Error string `json:"error,omitempty"`
}
