/*
Datadatdat API

REST API exposed by the local `datadatdat-server` Docker container and consumed by the Datadatdat CLI (`d3`) and other in-process clients.  The server listens on a loopback port only and is **not intended for remote use**; there is no authentication, authorization, or transport security. For multi-tenant or cross-host scenarios, deploy the separate `datadatdat-remote-server` instead, which fronts this API with auth.  Operation IDs follow `verbResource` naming (e.g. `listRepositories`, `createCommit`) and map 1:1 to generated client methods.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package datadatdatclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RemoteParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteParameters{}

// RemoteParameters struct for RemoteParameters
type RemoteParameters struct {
	// Remote type
	Provider string `json:"provider"`
	// Provider-specific remote properties
	Properties map[string]interface{} `json:"properties"`
}

type _RemoteParameters RemoteParameters

// NewRemoteParameters instantiates a new RemoteParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteParameters(provider string, properties map[string]interface{}) *RemoteParameters {
	this := RemoteParameters{}
	this.Provider = provider
	this.Properties = properties
	return &this
}

// NewRemoteParametersWithDefaults instantiates a new RemoteParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteParametersWithDefaults() *RemoteParameters {
	this := RemoteParameters{}
	return &this
}

// GetProvider returns the Provider field value
func (o *RemoteParameters) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *RemoteParameters) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *RemoteParameters) SetProvider(v string) {
	o.Provider = v
}

// GetProperties returns the Properties field value
func (o *RemoteParameters) GetProperties() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *RemoteParameters) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// SetProperties sets field value
func (o *RemoteParameters) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

func (o RemoteParameters) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["provider"] = o.Provider
	toSerialize["properties"] = o.Properties
	return toSerialize, nil
}

func (o *RemoteParameters) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"provider",
		"properties",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoteParameters := _RemoteParameters{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoteParameters)

	if err != nil {
		return err
	}

	*o = RemoteParameters(varRemoteParameters)

	return err
}

type NullableRemoteParameters struct {
	value *RemoteParameters
	isSet bool
}

func (v NullableRemoteParameters) Get() *RemoteParameters {
	return v.value
}

func (v *NullableRemoteParameters) Set(val *RemoteParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteParameters(val *RemoteParameters) *NullableRemoteParameters {
	return &NullableRemoteParameters{value: val, isSet: true}
}

func (v NullableRemoteParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
